sonar.projectKey=CassioCintra_ms-feature-flags-management
sonar.organization=cassiocintra
sonar.projectName=ms-feature-flags-management

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/config/**,**/*Application.java
sonar.coverage.exclusions=**/config/**,**/*Application.java,**/domain/exception/**
